language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
 - curl -s https://getcomposer.org/installer | php
 - php composer.phar install
 - cp config/zfcuserldap.global.php.dist tests/config/autoload/zfcuserldap.global.php
 - mkdir data
 - mkdir data/logs
 - cd tests

script:
 - phpunit

